### ISSUE TITLE
img with non-relative src attributes don't fail the analyzer

### ISSUE THREAD

**Issue by nathanyoung** [CenturyLinkCloud/KB-Commit-Analyzer#3]
KB authors are referencing images with the ctl.io location of images, when they should be using the PublicKB/APIDoc/Getting-Started relative paths to the source of the image. This results in broken images when viewing articles in Github.

(Line 17) https://github.com/CenturyLinkCloud/PublicKB/edit/master/Ecosystem%20Partners/Marketplace%20Guides/getting-started-with-pivotal-cloud-foundry.md

**Comment by nathanyoung** [comment]
cc @mattfordham

**Comment by mattfordham** [comment]
Thanks @nathanyoung  We're planning on addressing this, along with a few other misc items on Friday. Is that ok?

**Comment by thenickcox** [comment]
Closed via ccacf69b0e8be4b91c8dba0cffdbab2ae3993832
